test_0 (__main__.lab1a.test_0)
[Lab 1] - [Investigation 3] - [Part 2] - printing - Test for file creation: ./lab1a.py ... ok
test_a (__main__.lab1a.test_a)
[Lab 1] - [Investigation 3] - [Part 2] - printing - Test for errors running: ./lab1a.py ... /usr/lib/python3.12/subprocess.py:822: ResourceWarning: unclosed file <_io.TextIOWrapper name=3 encoding='UTF-8'>
  _cleanup()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
ok
test_a1 (__main__.lab1a.test_a1)
[Lab 1] - [Investigation 3] - [Part 2] - printing - Test for correct shebang line: ./lab1a.py ... ok
test_b (__main__.lab1a.test_b)
[Lab 1] - [Investigation 3] - [Part 2] - printing - Test output for correct output "Hello world": ./lab1a.py ... FAIL

======================================================================
FAIL: test_b (__main__.lab1a.test_b)
[Lab 1] - [Investigation 3] - [Part 2] - printing - Test output for correct output "Hello world": ./lab1a.py
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kbay/ops445/lab1/./CheckLab1.py", line 90, in test_b
    self.assertEqual(stdout, expected_output, msg=error_output)
AssertionError: b'Hello world\nHow old are you Isaac?\n' != b'Hello world\n' : output is not correct(HINT: pay attention to uppercase letters, spaces, and symbols)

----------------------------------------------------------------------
Ran 4 tests in 0.031s

FAILED (failures=1)
OPS445 Lab Report - System Information for running ./CheckLab1.py
=================================================================
    User login name: kbay
    Git Email: kbay@myseneca.ca
    Linux system name: kbay-VirtualBox
    Python executable: /usr/bin/python3
    Python version:  3.12.3 (main, Feb  4 2025, 14:48:35) [GCC 13.3.0]
    OS Platform: linux
    Working Directory: /home/kbay/ops445/lab1
    Start at: Mon May 12 13:35:18 2025
=================================================================
